
a = {1:"a"}
print(a[2]) # must be error.